name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.x

      - name: checkout
        uses: actions/checkout@v1

      - name: build
        run: |
          GOOS=windows GOARCH=amd64 go build -ldflags '-s -w -extldflags "-static"' -o bin/ci-test-windows-amd64.exe
          GOOS=darwin  GOARCH=amd64 go build -ldflags '-s -w -extldflags "-static"' -o bin/ci-test-darwin-amd64
          GOOS=linux   GOARCH=amd64 go build -ldflags '-s -w -extldflags "-static"' -o bin/ci-test-linux-amd64

      - name: Deploy Beta - Windows
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: https://uploads.github.com/repos/Mikubill/transfer/releases/43093978/assets{?name,label}
          release_id: 43093978
          asset_path: ./bin/ci-test-windows-amd64.exe
          asset_name: transfer-beta-windows-amd64-$$.exe 
          asset_content_type: application/octet-stream             
          max_releases: 1

      - name: Deploy Beta - Linux
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: https://uploads.github.com/repos/Mikubill/transfer/releases/43093978/assets{?name,label}
          release_id: 43093978
          asset_path: ./bin/ci-test-linux-amd64
          asset_name: transfer-beta-linux-amd64-$$
          asset_content_type: application/octet-stream 
          max_releases: 1

      - name: Deploy Beta - Macos
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: https://uploads.github.com/repos/Mikubill/transfer/releases/43093978/assets{?name,label}
          release_id: 43093978
          asset_path: ./bin/ci-test-darwin-amd64
          asset_name: transfer-beta-darwin-amd64-$$
          asset_content_type: application/octet-stream 
          max_releases: 1
